### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by jerizm** [jerizm/dotfiles#1]
- [ ] scripts to install cmake, vim, git 
- [ ] compile youcompleteme
- [x] login scripts to update prezto and dotfiles daily (look at ohmyzsh?)
- [x] login scripts to run docker dev
- [x] install ag
